name: Notify Slack on Failure

on:
  workflow_run:
    workflows:
      - "Publish to Docker"  # Replace with your actual workflow name
    types:
      - completed

jobs:
  notify-slack:
    if: ${{ failure() }}  # Trigger this job only on failure
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text": "🚨 Workflow *${{ github.workflow }}* in repository *${{ github.repository }}* failed.\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View details here>."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
