name: Publish to Docker
on:
  push:
    branches:
      - main
permissions:
  packages: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Add your test steps here if needed...
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/Learning-p/publish-packages/game
          tags: type=sha
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  notify-slack:
    # Always runs, but the payload depends on success/failure
    runs-on: ubuntu-latest
    if: ${{ failure() }}  # This job runs only when a previous job fails
    steps:
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "🚨 A job in the *${{ github.workflow }}* workflow failed!\nJob: *${{ job.name }}*\nRepository: *${{ github.repository }}*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View details here>."
          }' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

